#!/usr/bin/env bash
#
# npg_langqc devcontainer — create frontend/.env before the image builds.
#
# The frontend's development Dockerfile stage does `COPY ./.env` at BUILD time,
# which happens before postCreate/setup.sh runs. This script is wired to
# devcontainer.json "initializeCommand", which runs on the host before the
# containers are built, so the file exists in time. Existing files are left
# untouched.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$here")"
env_file="$repo_root/frontend/.env"

if [ -f "$env_file" ]; then
  echo "init_frontend_env: $env_file already exists; leaving as-is"
  exit 0
fi

# These VITE_ values are consumed by the UI for external links (SMRT Link and
# the Sequencescape LIMS). The targets are not reachable from the devcontainer;
# placeholder values just keep the build and the UI happy.
cat > "$env_file" <<'EOF'
VITE_SMRTLINK_PORT=8243
VITE_LIMS_SS_SERVER_URL=https://sequencescape.example.com
EOF

echo "init_frontend_env: created $env_file"
