# npg_langqc devcontainer — create the MLWH (multi-LIMS warehouse) schema.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31

"""Create the MLWH schema in the devcontainer database.

The MLWH has no Alembic migrations in this repository — the ORM metadata is the
source of truth (see tests/conftest.py), so the tables are created directly from
``lang_qc.db.mlwh_schema.Base``. This is idempotent: ``create_all`` only creates
tables that are missing and leaves existing ones (and their data) untouched.
"""

import os
import sys

from sqlalchemy import create_engine, text

from lang_qc.db.mlwh_schema import Base as MlwhBase

url = os.environ.get("DB_URL")
if not url:
    sys.exit("DB_URL must be set to the MLWH database URL")

engine = create_engine(url)

# Set sql_mode and run the DDL on the SAME connection: parts of the MLWH schema
# carry zero-date values that MySQL's default strict mode rejects, so relax it
# for this session (mirrors the workaround in tests/conftest.py).
with engine.begin() as conn:
    conn.execute(text("SET sql_mode = ''"))
    MlwhBase.metadata.create_all(bind=conn)

print("MLWH schema ready")
