# npg_langqc devcontainer — load a minimal dev dataset.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31

"""Load a small, self-consistent dataset for local development.

This is a *fresh* minimal fixture set (not the test data): one run with two
completed, not-yet-QC'd wells, each with a sample/study and product metrics,
plus a couple of QC users so auth-gated endpoints resolve.

Two things are done programmatically rather than as static YAML, on purpose:

* ``id_pac_bio_product`` is computed with ``npg_id_generation`` so it is the
  canonical product hash the application expects (not an arbitrary string).
* Run/well timestamps are set relative to "now" so the wells fall inside the
  inbox's 12-week look-back window and actually appear in the UI. Static dates
  would silently age out.

Idempotent: if the dev run already exists the MLWH load is skipped, and users
are only added if missing.
"""

import datetime
import os
import sys

from sqlalchemy import create_engine, select, text
from sqlalchemy.orm import Session

from lang_qc.db.mlwh_schema import (
    PacBioProductMetrics,
    PacBioRun,
    PacBioRunWellMetrics,
    Sample,
    Study,
)
from lang_qc.db.qc_schema import User

try:
    from npg_id_generation.pac_bio import PacBioEntity
except ImportError:  # pragma: no cover - dev dependency must be installed
    sys.exit('npg_id_generation is required; run `pip install ".[test]"` first')

# --- Fixture definition --------------------------------------------------
RUN_NAME = "DEV-RUN-1"
PLATE_NUMBER = 1
# (well_label, sample display name)
WELLS = [("A1", "dev_sample_A1"), ("B1", "dev_sample_B1")]

# QC users; the username IS the OIDC email that check_user() matches against.
# The devcontainer proxy injects one of these as the dev identity.
DEV_USERS = ["dev@example.com", "qc-team@example.com"]


def product_id(well_label: str) -> str:
    """Canonical PacBio product id for a well on the dev run."""
    return PacBioEntity(
        run_name=RUN_NAME, well_label=well_label, plate_number=PLATE_NUMBER
    ).hash_product_id()


def load_qc_users(qcdb_url: str) -> None:
    engine = create_engine(qcdb_url)
    with Session(engine) as session:
        existing = set(session.execute(select(User.username)).scalars())
        added = [u for u in DEV_USERS if u not in existing]
        for username in added:
            session.add(User(username=username))
        session.commit()
    print(
        f"QC users: {len(added)} added, {len(DEV_USERS) - len(added)} already present"
    )


def load_mlwh_fixtures(mlwh_url: str) -> None:
    engine = create_engine(mlwh_url)
    now = datetime.datetime.now()
    # Recent so the wells land inside the inbox look-back window.
    run_start = now - datetime.timedelta(days=4)
    run_complete = now - datetime.timedelta(days=3)

    with Session(engine) as session:
        # Some MLWH columns carry zero-date values MySQL strict mode rejects.
        session.execute(text("SET sql_mode = ''"))

        already = session.execute(
            select(PacBioRunWellMetrics).where(
                PacBioRunWellMetrics.pac_bio_run_name == RUN_NAME
            )
        ).first()
        if already:
            print(f"MLWH fixtures already present for run {RUN_NAME}; skipping")
            return

        study = Study(
            id_lims="SQSCP",
            id_study_lims="DEV1",
            uuid_study_lims="dev-study-uuid-0001",
            name="Dev Study",
            last_updated=now,
            recorded_at=now,
        )
        session.add(study)
        session.flush()  # populate study.id_study_tmp

        for index, (well_label, sample_name) in enumerate(WELLS, start=1):
            sample = Sample(
                id_lims="SQSCP",
                id_sample_lims=f"DEVS{index}",
                uuid_sample_lims=f"dev-sample-uuid-{index:04d}",
                name=sample_name,
                supplier_name=sample_name,
                last_updated=now,
                recorded_at=now,
            )
            session.add(sample)
            session.flush()  # populate sample.id_sample_tmp

            run = PacBioRun(
                last_updated=now,
                recorded_at=now,
                id_sample_tmp=sample.id_sample_tmp,
                id_study_tmp=study.id_study_tmp,
                id_pac_bio_run_lims="DEV1",
                cost_code="S1234",
                id_lims="SQSCP",
                plate_uuid_lims=f"dev-plate-uuid-{index:04d}",
                well_label=well_label,
                well_uuid_lims=f"dev-well-uuid-{index:04d}",
                pac_bio_library_tube_id_lims=f"DEV-LT-{index}",
                pac_bio_library_tube_uuid=f"dev-lt-uuid-{index:04d}",
                pac_bio_library_tube_name=sample_name,
                pac_bio_run_name=RUN_NAME,
                plate_number=PLATE_NUMBER,
            )
            session.add(run)
            session.flush()  # populate run.id_pac_bio_tmp

            pid = product_id(well_label)
            well = PacBioRunWellMetrics(
                id_pac_bio_product=pid,
                pac_bio_run_name=RUN_NAME,
                well_label=well_label,
                plate_number=PLATE_NUMBER,
                instrument_type="Revio",
                instrument_name="dev-instrument",
                movie_name=f"m_dev_{well_label}",
                movie_minutes=1440,
                # Inbox visibility: Complete + not-yet-QC'd + recent + reads present,
                # with ccs_execution_mode "None" so no hifi metrics are required.
                well_status="Complete",
                run_status="Complete",
                ccs_execution_mode="None",
                run_start=run_start,
                run_complete=run_complete,
                well_start=run_start,
                well_complete=run_complete,
                polymerase_num_reads=500000,
                polymerase_read_length_mean=95000,
                p1_num=480000,
            )
            session.add(well)
            session.flush()  # populate well.id_pac_bio_rw_metrics_tmp

            session.add(
                PacBioProductMetrics(
                    id_pac_bio_rw_metrics_tmp=well.id_pac_bio_rw_metrics_tmp,
                    id_pac_bio_tmp=run.id_pac_bio_tmp,
                    id_pac_bio_product=pid,
                )
            )

        session.commit()
    print(f"MLWH fixtures: loaded run {RUN_NAME} with {len(WELLS)} wells")


def main() -> None:
    qcdb_url = os.environ.get("QCDB_URL")
    mlwh_url = os.environ.get("DB_URL")
    if not qcdb_url or not mlwh_url:
        sys.exit("QCDB_URL and DB_URL must both be set")

    load_qc_users(qcdb_url)
    load_mlwh_fixtures(mlwh_url)


if __name__ == "__main__":
    main()
