#!/usr/bin/env bash
#
# npg_langqc devcontainer — post-create setup.
#
# Runs once (via devcontainer.json "postCreateCommand") after the container is
# built. Installs dependencies and waits for the databases to be ready. Schema
# creation, fixtures and the app/proxy services are wired in by later steps.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31
# Last modified by: Claude Opus 4.8 (1M context)
# Last modified:    2026-07-31

set -euo pipefail

echo "==> npg_langqc devcontainer setup"

# --- Wait for a TCP service to accept connections ------------------------
# Uses bash's /dev/tcp so no mysql client is required in the workspace image.
wait_for_tcp() {
  local host=$1 port=$2 name=$3
  echo "==> Waiting for ${name} (${host}:${port})"
  for _ in $(seq 1 60); do
    if (echo > "/dev/tcp/${host}/${port}") >/dev/null 2>&1; then
      echo "    ${name} is accepting connections"
      return 0
    fi
    sleep 2
  done
  echo "    ERROR: ${name} did not become ready in time" >&2
  return 1
}

# --- Backend dependencies (Poetry) ---------------------------------------
# Mirror CI: install Poetry via pipx, then install into a project virtualenv.
if ! command -v poetry >/dev/null 2>&1; then
  echo "==> Installing Poetry"
  pipx install poetry
fi

echo "==> Installing backend dependencies (poetry install)"
poetry env use 3.10
poetry install

# --- Frontend dependencies (npm) -----------------------------------------
echo "==> Installing frontend dependencies (npm install)"
( cd frontend && npm install )

# --- Databases -----------------------------------------------------------
# compose depends_on already gates on healthchecks, but wait explicitly so a
# failure here is obvious in the setup log. Hostnames are the compose service
# names; ports match docker-compose.yml (3306 MLWH, 3307 QC).
wait_for_tcp mlwh_db 3306 "MLWH database"
wait_for_tcp qc_db 3307 "QC database"

# --- Database schemas ----------------------------------------------------
# QC database: Alembic builds the schema AND seeds the dictionary tables
# (seq_platform, qc_type, qc_state_dict, ...) via its migrations. Reads
# ALEMBIC_DB_URL from the environment (see alembic/env.py). Idempotent.
echo "==> Applying QC database migrations (alembic upgrade head)"
poetry run alembic upgrade head

# MLWH database: no migrations exist, so create the schema from the ORM.
echo "==> Creating MLWH schema"
poetry run python .devcontainer/init_mlwh_schema.py

echo "==> Setup complete"
