#!/usr/bin/env bash
#
# npg_langqc devcontainer — post-create setup.
#
# Runs once (via devcontainer.json "postCreateCommand") after the container is
# built: installs dependencies, waits for the databases, applies migrations and
# loads dev fixtures.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31
# Last modified by: Claude Opus 4.8 (1M context)
# Last modified:    2026-08-13

set -euo pipefail

echo "==> npg_langqc devcontainer setup"

# --- Wait for a TCP service to accept connections ------------------------
# Uses bash's /dev/tcp so no mysql client is required in the workspace image.
wait_for_tcp() {
  local host=$1 port=$2 name=$3
  echo "==> Waiting for ${name} (${host}:${port})"
  # Generous window: a fresh MySQL data-dir init under first-build load can take
  # a few minutes. Loop exits as soon as the port opens, so this only waits as
  # long as needed. 180 * 2s = up to 6 minutes.
  for _ in $(seq 1 180); do
    if (echo > "/dev/tcp/${host}/${port}") >/dev/null 2>&1; then
      echo "    ${name} is accepting connections"
      return 0
    fi
    sleep 2
  done
  echo "    ERROR: ${name} did not become ready in time" >&2
  return 1
}

# --- Backend dependencies ------------------------------------------------
# Editable install of the project and its "test" extra (alembic and
# npg_id_generation, used below) so lang_qc imports from the mounted source.
echo "==> Installing backend dependencies (pip install)"
pip install --editable ".[test]"

# --- Frontend dependencies (npm) -----------------------------------------
echo "==> Installing frontend dependencies (npm install)"
( cd frontend && npm install )

# --- Databases -----------------------------------------------------------
# depends_on only orders startup, it does not wait for readiness, so wait here.
# Hostnames are the compose service names (ports 3306 MLWH, 3307 QC).
wait_for_tcp mlwh_db 3306 "MLWH database"
wait_for_tcp qc_db 3307 "QC database"

# --- Database schemas ----------------------------------------------------
# QC database: Alembic builds the schema AND seeds the dictionary tables
# (seq_platform, qc_type, qc_state_dict, ...) via its migrations. Reads
# ALEMBIC_DB_URL from the environment (see alembic/env.py). Idempotent.
#
# Use "heads" (plural), not "head": the migration tree branches at
# dd60c67ad3e5 into two unmerged heads (23c7eda792e2 and 2.1.0), so the
# singular "head" target fails with "Multiple head revisions are present".
echo "==> Applying QC database migrations (alembic upgrade heads)"
alembic upgrade heads

# MLWH database: no migrations exist, so create the schema from the ORM.
echo "==> Creating MLWH schema"
python .devcontainer/init_mlwh_schema.py

# --- Fixtures ------------------------------------------------------------
# Load a minimal dev dataset (one run, two inbox-ready wells) plus QC users.
echo "==> Loading dev fixtures"
python .devcontainer/load_fixtures.py

echo "==> Setup complete"
