#!/usr/bin/env bash
#
# npg_langqc devcontainer — post-create setup.
#
# Runs once (via devcontainer.json "postCreateCommand") after the container is
# built. Step 1 only installs dependencies; schema creation, fixtures and the
# app/proxy services are wired in by later steps.
#
# Generated by:    Claude Opus 4.8 (1M context)
# Generation date: 2026-07-31

set -euo pipefail

echo "==> npg_langqc devcontainer setup"

# --- Backend dependencies (Poetry) ---------------------------------------
# Mirror CI: install Poetry via pipx, then install into a project virtualenv.
if ! command -v poetry >/dev/null 2>&1; then
  echo "==> Installing Poetry"
  pipx install poetry
fi

echo "==> Installing backend dependencies (poetry install)"
poetry env use 3.10
poetry install

# --- Frontend dependencies (npm) -----------------------------------------
echo "==> Installing frontend dependencies (npm install)"
( cd frontend && npm install )

echo "==> Setup complete"
